index:
    path: /
    controller: App\Controller\DefaultController::index

countries:
    path: /countries
    controller: App\Controller\CountriesController::index

weather:
    path: /weather
    controller: App\Controller\WeatherController::index